version: '3.3'

services:
  mqtt-dashboard:
    container_name: front-mqtt
    build: .
    ports:
      - "8082:80"
    networks:
      - mynetwork

networks:
      mynetwork:
        external: true
